<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%
String invoice_no      = request.getParameter("invoice_no");
String booking_date    = request.getParameter("booking_date");
String delivery_date   = request.getParameter("delivery_date");
String cust_id         = request.getParameter("cust_id");
String full_name       = request.getParameter("full_name");
String address         = request.getParameter("address");
String v_no            = request.getParameter("v_no");
String v_model         = request.getParameter("v_model");
String v_name          = request.getParameter("v_name");
String v_manu          = request.getParameter("v_manu");
String engine_no       = request.getParameter("engine_no");
String chasis_no       = request.getParameter("chasis_no");
String rcbook_no       = request.getParameter("rcbook_no");
String engine_cap      = request.getParameter("engine_cap");
String colors          = request.getParameter("colors");
String free_serv       = request.getParameter("free_serv");
String payment_mode    = request.getParameter("payment_mode");
String bank_name       = request.getParameter("bank_name");
String ifsc_code       = request.getParameter("ifsc_code");
String cheque_date     = request.getParameter("cheque_date");
String cheque_no       = request.getParameter("cheque_no");
String price           = request.getParameter("price");
String first_install   = request.getParameter("first_install");
String second_install  = request.getParameter("second_install");
String third_install   = request.getParameter("third_install");
String cgst            = request.getParameter("cgst");
String sgst            = request.getParameter("sgst");
String balance         = request.getParameter("balance");
String grand_total     = request.getParameter("grand_total");

out.print("<html>");
out.print("<head>");
out.print("<title>Invoice JSP</title>");
out.print("</head>");
out.print("<body>");
out.println("<table border='1' align='center' width='600'>");
out.println("<tr><td colspan='2'><img src='bike2.jpg' alt='Smiley face' height='80' width='225' align='middle'><center><h1><b>BIKE SALES SYSTEM</b></h1></center></td></tr>");
out.println("<tr><td>Invoice No</td><td>"+invoice_no+"</td></tr>");
out.println("<tr><td>Booking Date</td><td>"+booking_date+"</td></tr>");
out.println("<tr><td>Delivery Date</td><td>"+delivery_date+"</td></tr>");
out.println("<tr><td>Customer Id</td><td>"+cust_id+"</td></tr>");
out.println("<tr><td>Full Name</td><td>"+full_name+"</td></tr>");
out.println("<tr><td>Address </td><td>"+address+"</td></tr>");
out.println("<tr><td>Vehicle No</td><td>"+v_no +"</td></tr>");
out.println("<tr><td>Vehicle Model</td><td>"+v_model+"</td></tr>");
out.println("<tr><td>Vehile Name</td><td>"+v_name +"</td></tr>");
out.println("<tr><td>Vehicle Manufacture</td><td>"+v_manu+"</td></tr>");
out.println("<tr><td>Engine No</td><td>"+engine_no+"</td></tr>");
out.println("<tr><td>Chasis No</td><td>"+chasis_no +"</td></tr>");
out.println("<tr><td>RCBOOK NO</td><td>"+rcbook_no+"</td></tr>");
out.println("<tr><td>Engine cap</td><td>"+engine_cap+"</td></tr>");
out.println("<tr><td>Colors</td><td>"+colors +"</td></tr>");
out.println("<tr><td>Free Services</td><td>"+free_serv +"</td></tr>");
out.println("<tr><td>Payment Mode</td><td>"+payment_mode+"</td></tr>");
out.println("<tr><td>Bank Name</td><td>"+bank_name+"</td></tr>");
out.println("<tr><td>Bank Ifsc Code</td><td>"+ifsc_code +"</td></tr>");
out.println("<tr><td>Cheque Date</td><td>"+cheque_date+"</td></tr>");
out.println("<tr><td>Cheque No</td><td>"+cheque_no+"</td></tr>");
out.println("<tr><td>Price</td><td>"+ price +"</td></tr>");
out.println("<tr><td>First Installment</td><td>"+first_install+"</td></tr>");
out.println("<tr><td>Second Installment</td><td>"+second_install+"</td></tr>");
out.println("<tr><td>Third Installment</td><td>"+third_install+"</td></tr>");
out.println("<tr><td>CGST</td><td>"+cgst+"</td></tr>");
out.println("<tr><td>SGST</td><td>"+sgst+"</td></tr>");
out.println("<tr><td>balance</td><td>"+balance+"</td></tr>");
out.println("<tr><td>grand_total</td><td>"+grand_total+"</td></tr>");
out.println("<tr><td colspan='2' height='100' align='right'>Authorised Signature</td></tr>");
out.println("</table>");
out.print("</body>");
out.print("</html>");
%>
